// Realistic-ish seed data for SkillPath. Small enough to comfortably fit
// a CognoDB free (c0) instance, rich enough to make every multi-hop query
// in the app return something meaningful.

export const skills = [
  { id: "sk_python", name: "Python", category: "Programming" },
  { id: "sk_js", name: "JavaScript", category: "Programming" },
  { id: "sk_ts", name: "TypeScript", category: "Programming" },
  { id: "sk_go", name: "Go", category: "Programming" },
  { id: "sk_java", name: "Java", category: "Programming" },
  { id: "sk_sql", name: "SQL", category: "Programming" },
  { id: "sk_git", name: "Version Control (Git)", category: "Programming" },
  { id: "sk_system_design", name: "System Design", category: "Programming" },

  { id: "sk_data_analysis", name: "Data Analysis", category: "Data" },
  { id: "sk_statistics", name: "Statistics", category: "Data" },
  { id: "sk_ml", name: "Machine Learning", category: "Data" },
  { id: "sk_deep_learning", name: "Deep Learning", category: "Data" },
  { id: "sk_data_viz", name: "Data Visualization", category: "Data" },
  { id: "sk_etl", name: "ETL Pipelines", category: "Data" },

  { id: "sk_aws", name: "AWS", category: "Cloud & DevOps" },
  { id: "sk_docker", name: "Docker", category: "Cloud & DevOps" },
  { id: "sk_k8s", name: "Kubernetes", category: "Cloud & DevOps" },
  { id: "sk_terraform", name: "Terraform", category: "Cloud & DevOps" },
  { id: "sk_cicd", name: "CI/CD", category: "Cloud & DevOps" },
  { id: "sk_linux", name: "Linux Administration", category: "Cloud & DevOps" },
  { id: "sk_security", name: "Cybersecurity", category: "Cloud & DevOps" },

  { id: "sk_ui_design", name: "UI Design", category: "Design" },
  { id: "sk_figma", name: "Figma", category: "Design" },
  { id: "sk_design_systems", name: "Design Systems", category: "Design" },
  { id: "sk_ux_research", name: "UX Research", category: "Design" },

  { id: "sk_product_strategy", name: "Product Strategy", category: "Product" },
  { id: "sk_roadmapping", name: "Roadmapping", category: "Product" },
  { id: "sk_stakeholder_mgmt", name: "Stakeholder Management", category: "Product" },
  { id: "sk_agile", name: "Agile / Scrum", category: "Product" },

  { id: "sk_communication", name: "Communication", category: "Soft Skills" },
  { id: "sk_leadership", name: "Leadership", category: "Soft Skills" },
  { id: "sk_mentoring", name: "Mentoring", category: "Soft Skills" },
  { id: "sk_tech_writing", name: "Technical Writing", category: "Soft Skills" },
];

// Undirected adjacency in practice; stored as one directed edge each with a
// 1–5 "how related" strength. This is the graph the pathway finder and
// skill-map traversals walk.
export const skillRelations = [
  ["sk_python", "sk_data_analysis", 4],
  ["sk_python", "sk_ml", 4],
  ["sk_python", "sk_etl", 3],
  ["sk_data_analysis", "sk_statistics", 5],
  ["sk_statistics", "sk_ml", 4],
  ["sk_ml", "sk_deep_learning", 5],
  ["sk_data_analysis", "sk_data_viz", 4],
  ["sk_sql", "sk_data_analysis", 4],
  ["sk_sql", "sk_etl", 4],
  ["sk_etl", "sk_python", 3],
  ["sk_sql", "sk_java", 2],

  ["sk_js", "sk_ts", 5],
  ["sk_ts", "sk_system_design", 2],
  ["sk_java", "sk_system_design", 3],
  ["sk_go", "sk_system_design", 3],
  ["sk_git", "sk_cicd", 3],
  ["sk_cicd", "sk_docker", 4],
  ["sk_docker", "sk_k8s", 5],
  ["sk_k8s", "sk_aws", 4],
  ["sk_aws", "sk_terraform", 4],
  ["sk_terraform", "sk_cicd", 3],
  ["sk_k8s", "sk_system_design", 3],
  ["sk_aws", "sk_system_design", 3],
  ["sk_linux", "sk_aws", 3],
  ["sk_linux", "sk_security", 4],
  ["sk_security", "sk_aws", 3],

  ["sk_ui_design", "sk_figma", 5],
  ["sk_figma", "sk_design_systems", 4],
  ["sk_design_systems", "sk_ux_research", 3],
  ["sk_ux_research", "sk_product_strategy", 3],
  ["sk_product_strategy", "sk_roadmapping", 5],
  ["sk_roadmapping", "sk_stakeholder_mgmt", 4],
  ["sk_stakeholder_mgmt", "sk_communication", 4],
  ["sk_communication", "sk_leadership", 4],
  ["sk_leadership", "sk_mentoring", 5],
  ["sk_mentoring", "sk_tech_writing", 3],
  ["sk_agile", "sk_stakeholder_mgmt", 3],
  ["sk_agile", "sk_roadmapping", 3],
  ["sk_tech_writing", "sk_communication", 4],
];

export const companies = [
  { id: "co_nimbus", name: "Nimbus Cloud Systems", industry: "Cloud Infrastructure" },
  { id: "co_northwind", name: "Northwind Analytics", industry: "Data & Analytics" },
  { id: "co_brightpath", name: "BrightPath Health Tech", industry: "Healthcare" },
  { id: "co_fernwood", name: "Fernwood Robotics", industry: "Robotics" },
  { id: "co_lumen", name: "Lumen Financial", industry: "Fintech" },
  { id: "co_cascade", name: "Cascade Studio", industry: "Design Agency" },
  { id: "co_anchorline", name: "Anchorline Logistics", industry: "Logistics" },
  { id: "co_solstice", name: "Solstice Games", industry: "Gaming" },
];

export const jobs = [
  {
    id: "job_backend_sr", title: "Senior Backend Engineer", level: "Senior",
    company: "co_nimbus",
    description: "Own core services powering Nimbus's platform APIs, with a focus on reliability at scale.",
    skills: [["sk_go", 3], ["sk_system_design", 3], ["sk_docker", 2], ["sk_k8s", 2], ["sk_sql", 2], ["sk_git", 1]],
  },
  {
    id: "job_platform_eng", title: "Platform Engineer", level: "Mid",
    company: "co_nimbus",
    description: "Build and operate the internal platform that other engineering teams deploy on top of.",
    skills: [["sk_k8s", 3], ["sk_terraform", 3], ["sk_aws", 3], ["sk_cicd", 2], ["sk_linux", 2]],
  },
  {
    id: "job_security_eng", title: "Security Engineer", level: "Mid",
    company: "co_nimbus",
    description: "Harden infrastructure and lead incident response across Nimbus's cloud footprint.",
    skills: [["sk_security", 3], ["sk_linux", 3], ["sk_aws", 2], ["sk_system_design", 1]],
  },
  {
    id: "job_data_scientist", title: "Data Scientist", level: "Mid",
    company: "co_northwind",
    description: "Build forecasting and churn models for Northwind's analytics clients.",
    skills: [["sk_python", 3], ["sk_ml", 3], ["sk_statistics", 3], ["sk_sql", 2], ["sk_data_viz", 1]],
  },
  {
    id: "job_ml_engineer_sr", title: "Senior Machine Learning Engineer", level: "Senior",
    company: "co_northwind",
    description: "Take models from notebook to production, owning training pipelines and serving infra.",
    skills: [["sk_python", 3], ["sk_deep_learning", 3], ["sk_ml", 3], ["sk_docker", 2], ["sk_aws", 2], ["sk_system_design", 1]],
  },
  {
    id: "job_data_analyst", title: "Data Analyst", level: "Junior",
    company: "co_northwind",
    description: "Turn raw client data into dashboards and clear, decision-ready analysis.",
    skills: [["sk_sql", 3], ["sk_data_analysis", 3], ["sk_data_viz", 2], ["sk_statistics", 1]],
  },
  {
    id: "job_data_eng", title: "Data Engineer", level: "Mid",
    company: "co_brightpath",
    description: "Design and maintain the ETL pipelines that feed BrightPath's clinical analytics.",
    skills: [["sk_python", 3], ["sk_sql", 3], ["sk_etl", 3], ["sk_aws", 2], ["sk_security", 1]],
  },
  {
    id: "job_fullstack", title: "Full-Stack Engineer", level: "Mid",
    company: "co_brightpath",
    description: "Ship patient-facing features end to end across a TypeScript web stack.",
    skills: [["sk_ts", 3], ["sk_js", 2], ["sk_sql", 2], ["sk_system_design", 1], ["sk_git", 1]],
  },
  {
    id: "job_robotics_sw", title: "Robotics Software Engineer", level: "Senior",
    company: "co_fernwood",
    description: "Write control and perception software for Fernwood's warehouse robots.",
    skills: [["sk_python", 3], ["sk_system_design", 3], ["sk_linux", 2], ["sk_ml", 2], ["sk_git", 1]],
  },
  {
    id: "job_fintech_backend", title: "Backend Engineer, Payments", level: "Mid",
    company: "co_lumen",
    description: "Build the ledger and settlement services at the core of Lumen's payments product.",
    skills: [["sk_java", 3], ["sk_sql", 3], ["sk_system_design", 2], ["sk_security", 2], ["sk_cicd", 1]],
  },
  {
    id: "job_product_designer", title: "Product Designer", level: "Mid",
    company: "co_cascade",
    description: "Lead end-to-end design for client engagements, from research to shipped UI.",
    skills: [["sk_figma", 3], ["sk_ui_design", 3], ["sk_ux_research", 2], ["sk_design_systems", 2]],
  },
  {
    id: "job_design_lead", title: "Design Systems Lead", level: "Senior",
    company: "co_cascade",
    description: "Own the design system Cascade ships to every client and mentor junior designers.",
    skills: [["sk_design_systems", 3], ["sk_figma", 3], ["sk_leadership", 2], ["sk_mentoring", 2], ["sk_ui_design", 1]],
  },
  {
    id: "job_pm_logistics", title: "Product Manager, Routing", level: "Mid",
    company: "co_anchorline",
    description: "Own the roadmap for Anchorline's route-optimization product line.",
    skills: [["sk_product_strategy", 3], ["sk_roadmapping", 3], ["sk_stakeholder_mgmt", 2], ["sk_agile", 2], ["sk_data_analysis", 1]],
  },
  {
    id: "job_eng_manager", title: "Engineering Manager", level: "Senior",
    company: "co_solstice",
    description: "Lead a team of gameplay engineers while staying hands-on with architecture reviews.",
    skills: [["sk_leadership", 3], ["sk_mentoring", 3], ["sk_system_design", 2], ["sk_communication", 2], ["sk_agile", 1]],
  },
  {
    id: "job_gameplay_eng", title: "Gameplay Engineer", level: "Junior",
    company: "co_solstice",
    description: "Implement gameplay systems and tools for Solstice's live-service title.",
    skills: [["sk_java", 2], ["sk_git", 2], ["sk_system_design", 1], ["sk_communication", 1]],
  },
];

// proficiency: Beginner | Intermediate | Advanced | Expert
export const people = [
  { id: "p_amara", name: "Amara Okoye", title: "Backend Engineer", company: "co_nimbus",
    bio: "Backend engineer focused on distributed systems and service reliability.",
    skills: [["sk_go", "Advanced", 4], ["sk_system_design", "Advanced", 4], ["sk_docker", "Advanced", 3], ["sk_k8s", "Intermediate", 2], ["sk_sql", "Intermediate", 3], ["sk_git", "Expert", 5]],
    courses: ["course_k8s_deep"] },
  { id: "p_devon", name: "Devon Marsh", title: "Platform Engineer", company: "co_nimbus",
    bio: "Keeps the internal platform humming — Terraform, Kubernetes, and a lot of on-call.",
    skills: [["sk_k8s", "Expert", 5], ["sk_terraform", "Advanced", 4], ["sk_aws", "Advanced", 4], ["sk_cicd", "Advanced", 3], ["sk_linux", "Advanced", 4]],
    courses: ["course_terraform_associate"] },
  { id: "p_priya", name: "Priya Nandan", title: "Junior DevOps Engineer", company: "co_nimbus",
    bio: "Two years into infrastructure work, learning toward a platform engineering track.",
    skills: [["sk_docker", "Intermediate", 2], ["sk_linux", "Intermediate", 2], ["sk_git", "Advanced", 3], ["sk_cicd", "Beginner", 1]],
    courses: [] },
  { id: "p_luca", name: "Luca Ferrari", title: "Security Analyst", company: "co_nimbus",
    bio: "Threat monitoring and hardening for cloud workloads.",
    skills: [["sk_security", "Advanced", 3], ["sk_linux", "Advanced", 4], ["sk_aws", "Intermediate", 2]],
    courses: ["course_security_fundamentals"] },

  { id: "p_helen", name: "Helen Zhao", title: "Senior Data Scientist", company: "co_northwind",
    bio: "Builds forecasting models and mentors newer data scientists.",
    skills: [["sk_python", "Expert", 6], ["sk_ml", "Expert", 5], ["sk_statistics", "Advanced", 5], ["sk_deep_learning", "Advanced", 3], ["sk_sql", "Advanced", 4], ["sk_data_viz", "Intermediate", 3]],
    courses: ["course_deep_learning_specialization"] },
  { id: "p_marcus", name: "Marcus Webb", title: "Data Analyst", company: "co_northwind",
    bio: "Client-facing analyst, strong in SQL and dashboarding, growing into modeling.",
    skills: [["sk_sql", "Advanced", 3], ["sk_data_analysis", "Advanced", 3], ["sk_data_viz", "Advanced", 3], ["sk_statistics", "Beginner", 1]],
    courses: ["course_sql_for_analytics"] },
  { id: "p_sofia", name: "Sofia Reyes", title: "Machine Learning Engineer", company: "co_northwind",
    bio: "Takes models from research notebooks into production services.",
    skills: [["sk_python", "Advanced", 4], ["sk_ml", "Advanced", 3], ["sk_docker", "Intermediate", 2], ["sk_aws", "Intermediate", 2]],
    courses: ["course_mlops_essentials"] },

  { id: "p_ravi", name: "Ravi Kumar", title: "Data Engineer", company: "co_brightpath",
    bio: "Builds and maintains the ETL pipelines feeding clinical analytics.",
    skills: [["sk_python", "Advanced", 4], ["sk_sql", "Advanced", 4], ["sk_etl", "Advanced", 4], ["sk_aws", "Intermediate", 2]],
    courses: ["course_data_engineering_aws"] },
  { id: "p_naomi", name: "Naomi Clarke", title: "Full-Stack Engineer", company: "co_brightpath",
    bio: "Ships patient-facing features across the TypeScript stack.",
    skills: [["sk_ts", "Advanced", 3], ["sk_js", "Advanced", 4], ["sk_sql", "Intermediate", 2], ["sk_git", "Advanced", 4]],
    courses: [] },
  { id: "p_owen", name: "Owen Bright", title: "Junior Data Engineer", company: "co_brightpath",
    bio: "A year into data engineering, still building out SQL and pipeline depth.",
    skills: [["sk_python", "Intermediate", 1], ["sk_sql", "Intermediate", 1]],
    courses: ["course_sql_for_analytics"] },

  { id: "p_isla", name: "Isla Fraser", title: "Robotics Software Engineer", company: "co_fernwood",
    bio: "Writes perception and control software for warehouse robots.",
    skills: [["sk_python", "Expert", 5], ["sk_system_design", "Advanced", 4], ["sk_linux", "Advanced", 3], ["sk_ml", "Intermediate", 2], ["sk_git", "Advanced", 3]],
    courses: [] },

  { id: "p_theo", name: "Theo Bergman", title: "Backend Engineer", company: "co_lumen",
    bio: "Works on ledger and settlement services for Lumen's payments platform.",
    skills: [["sk_java", "Advanced", 4], ["sk_sql", "Advanced", 4], ["sk_system_design", "Intermediate", 2], ["sk_security", "Beginner", 1]],
    courses: [] },
  { id: "p_grace", name: "Grace Adeyemi", title: "Junior Backend Engineer", company: "co_lumen",
    bio: "New to fintech, building up systems-design and security depth.",
    skills: [["sk_java", "Intermediate", 1], ["sk_sql", "Intermediate", 1], ["sk_git", "Intermediate", 1]],
    courses: [] },

  { id: "p_maya", name: "Maya Lindqvist", title: "Product Designer", company: "co_cascade",
    bio: "End-to-end designer across research, UI, and client delivery.",
    skills: [["sk_figma", "Expert", 5], ["sk_ui_design", "Advanced", 5], ["sk_ux_research", "Advanced", 3], ["sk_design_systems", "Intermediate", 2]],
    courses: ["course_design_systems_practice"] },
  { id: "p_felix", name: "Felix Moreau", title: "Design Systems Lead", company: "co_cascade",
    bio: "Owns Cascade's shared design system and mentors the design team.",
    skills: [["sk_design_systems", "Expert", 5], ["sk_figma", "Expert", 5], ["sk_leadership", "Advanced", 3], ["sk_mentoring", "Advanced", 3], ["sk_ui_design", "Advanced", 4]],
    courses: [] },
  { id: "p_junior_designer", name: "Nadia Petrov", title: "Junior Product Designer", company: "co_cascade",
    bio: "A year into product design, strong Figma skills, building toward research.",
    skills: [["sk_figma", "Advanced", 1], ["sk_ui_design", "Intermediate", 1]],
    courses: ["course_ux_research_basics"] },

  { id: "p_carla", name: "Carla Mendes", title: "Product Manager", company: "co_anchorline",
    bio: "Owns the roadmap for route-optimization features.",
    skills: [["sk_product_strategy", "Advanced", 4], ["sk_roadmapping", "Advanced", 4], ["sk_stakeholder_mgmt", "Advanced", 4], ["sk_agile", "Intermediate", 3], ["sk_data_analysis", "Beginner", 1]],
    courses: ["course_product_strategy"] },
  { id: "p_ben", name: "Ben Okafor", title: "Associate Product Manager", company: "co_anchorline",
    bio: "Early-career PM building toward a strategy and roadmapping role.",
    skills: [["sk_agile", "Intermediate", 2], ["sk_communication", "Advanced", 3], ["sk_stakeholder_mgmt", "Beginner", 1]],
    courses: [] },

  { id: "p_jonah", name: "Jonah Kessler", title: "Engineering Manager", company: "co_solstice",
    bio: "Leads a gameplay engineering team, still hands-on with architecture reviews.",
    skills: [["sk_leadership", "Expert", 5], ["sk_mentoring", "Advanced", 4], ["sk_system_design", "Advanced", 5], ["sk_communication", "Advanced", 4], ["sk_agile", "Intermediate", 3]],
    courses: [] },
  { id: "p_yuki", name: "Yuki Tanaka", title: "Gameplay Engineer", company: "co_solstice",
    bio: "Implements gameplay systems for Solstice's live-service title, aiming toward management.",
    skills: [["sk_java", "Advanced", 3], ["sk_git", "Advanced", 3], ["sk_system_design", "Intermediate", 2], ["sk_communication", "Intermediate", 2]],
    courses: ["course_leadership_for_engineers"] },
  { id: "p_omar", name: "Omar Haddad", title: "Junior Gameplay Engineer", company: "co_solstice",
    bio: "First engineering job, learning the codebase and Agile ceremonies.",
    skills: [["sk_java", "Beginner", 1], ["sk_git", "Intermediate", 1]],
    courses: [] },

  { id: "p_freelance_amelia", name: "Amelia Voss", title: "Freelance Data Analyst", company: null,
    bio: "Independent analyst working across several clients, exploring a move into ML.",
    skills: [["sk_sql", "Advanced", 5], ["sk_data_analysis", "Advanced", 5], ["sk_python", "Intermediate", 2], ["sk_data_viz", "Advanced", 4]],
    courses: ["course_ml_foundations"] },
];

export const courses = [
  { id: "course_k8s_deep", title: "Kubernetes in Depth", provider: "Cloud Academy",
    url: "https://learn.example.com/kubernetes-in-depth", duration_hours: 12, teaches: ["sk_k8s", "sk_docker"] },
  { id: "course_terraform_associate", title: "Terraform Associate Prep", provider: "Cloud Academy",
    url: "https://learn.example.com/terraform-associate", duration_hours: 10, teaches: ["sk_terraform", "sk_aws"] },
  { id: "course_security_fundamentals", title: "Cloud Security Fundamentals", provider: "SecureLearn",
    url: "https://learn.example.com/cloud-security-fundamentals", duration_hours: 8, teaches: ["sk_security", "sk_linux"] },
  { id: "course_deep_learning_specialization", title: "Deep Learning Specialization", provider: "OpenLearn University",
    url: "https://learn.example.com/deep-learning-specialization", duration_hours: 40, teaches: ["sk_deep_learning", "sk_ml"] },
  { id: "course_sql_for_analytics", title: "SQL for Analytics", provider: "DataCraft",
    url: "https://learn.example.com/sql-for-analytics", duration_hours: 6, teaches: ["sk_sql", "sk_data_analysis"] },
  { id: "course_mlops_essentials", title: "MLOps Essentials", provider: "DataCraft",
    url: "https://learn.example.com/mlops-essentials", duration_hours: 14, teaches: ["sk_ml", "sk_docker", "sk_aws"] },
  { id: "course_data_engineering_aws", title: "Data Engineering on AWS", provider: "Cloud Academy",
    url: "https://learn.example.com/data-engineering-aws", duration_hours: 16, teaches: ["sk_etl", "sk_aws", "sk_python"] },
  { id: "course_design_systems_practice", title: "Design Systems in Practice", provider: "Craft & Co.",
    url: "https://learn.example.com/design-systems-in-practice", duration_hours: 9, teaches: ["sk_design_systems", "sk_figma"] },
  { id: "course_ux_research_basics", title: "UX Research Basics", provider: "Craft & Co.",
    url: "https://learn.example.com/ux-research-basics", duration_hours: 7, teaches: ["sk_ux_research"] },
  { id: "course_product_strategy", title: "Product Strategy Foundations", provider: "OpenLearn University",
    url: "https://learn.example.com/product-strategy-foundations", duration_hours: 11, teaches: ["sk_product_strategy", "sk_roadmapping"] },
  { id: "course_leadership_for_engineers", title: "Leadership for Engineers", provider: "OpenLearn University",
    url: "https://learn.example.com/leadership-for-engineers", duration_hours: 8, teaches: ["sk_leadership", "sk_mentoring"] },
  { id: "course_ml_foundations", title: "Machine Learning Foundations", provider: "DataCraft",
    url: "https://learn.example.com/machine-learning-foundations", duration_hours: 18, teaches: ["sk_ml", "sk_statistics"] },
  { id: "course_system_design_interview", title: "System Design for Engineers", provider: "Cloud Academy",
    url: "https://learn.example.com/system-design-for-engineers", duration_hours: 10, teaches: ["sk_system_design"] },
  { id: "course_agile_delivery", title: "Agile Delivery in Practice", provider: "Craft & Co.",
    url: "https://learn.example.com/agile-delivery-in-practice", duration_hours: 5, teaches: ["sk_agile", "sk_stakeholder_mgmt"] },
];
